title: wack's space
description: My Personal Blog
author: w03k
logo: https://www.gravatar.com/avatar/3e16476c2a29901c74bad612da8b0f4d
github: https://github.com/imwack
about: Nice to meet you.

baseurl: #"wack.space"
url: wack.space #"imwack.github.io"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: w0_3k
  fb_appid: 


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
