title: wack's space
description: My Personal Blog
author: w03k
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/imwack
about: Nice to meet you.

baseurl: #"wack.space"
url: "imwack.github.io"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: w0_3k
  fb_appid: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
